name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: docker build -t servicenow-ai-app ./servicenow-mcp

    - name: Tag and Push to ECR
      run: |
        docker tag servicenow-ai-app:latest \
        433365435200.dkr.ecr.ap-south-1.amazonaws.com/servicenow-ai-app:${{ github.sha }}
        docker push \
        433365435200.dkr.ecr.ap-south-1.amazonaws.com/servicenow-ai-app:${{ github.sha }}